// <auto-generated />
using System;
using EXE201.Repository.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EXE201.Repository.Migrations
{
    [DbContext(typeof(ClothingRentalDbContext))]
    [Migration("20260211144454_addBookingRepo")]
    partial class addBookingRepo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EXE201.Repository.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("AddressText")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("BookingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TotalDepositAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TotalRentalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TotalSurcharge")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId")
                        .HasName("PK__Bookings__73951AED36BC3699");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EXE201.Repository.Models.BookingDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DamageFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("DepositAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("LateFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("OutfitSizeId")
                        .HasColumnType("int");

                    b.Property<int>("RentalPackageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("DetailId")
                        .HasName("PK__BookingD__135C316D5419AAA6");

                    b.HasIndex("BookingId");

                    b.HasIndex("OutfitSizeId");

                    b.HasIndex("RentalPackageId");

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0B23B1A770");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EXE201.Repository.Models.DepositTransaction", b =>
                {
                    b.Property<int>("TransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransId"));

                    b.Property<decimal?>("AmountDeducted")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("AmountHeld")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("AmountRefunded")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("DeductionReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransId")
                        .HasName("PK__DepositT__9E5DDB3C2FF64C49");

                    b.HasIndex("BookingId");

                    b.ToTable("DepositTransactions");
                });

            modelBuilder.Entity("EXE201.Repository.Models.LoyaltyTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PointsAmount")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId")
                        .HasName("PK__LoyaltyT__55433A6B56D97C43");

                    b.HasIndex("UserId");

                    b.ToTable("LoyaltyTransactions");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Outfit", b =>
                {
                    b.Property<int>("OutfitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutfitId"));

                    b.Property<decimal>("BaseRentalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("IsLimited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OutfitId")
                        .HasName("PK__Outfits__399B99B1D4698121");

                    b.HasIndex("CategoryId");

                    b.ToTable("Outfits");
                });

            modelBuilder.Entity("EXE201.Repository.Models.OutfitAttribute", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("ColorPrimary")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CulturalOrigin")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FormalityLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Material")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Occasion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OutfitId")
                        .HasColumnType("int");

                    b.Property<string>("SeasonSuitability")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Silhouette")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StoryContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoryTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DetailId")
                        .HasName("PK__OutfitAt__135C316DBB0CECC4");

                    b.HasIndex(new[] { "OutfitId" }, "UQ__OutfitAt__399B99B01351115C")
                        .IsUnique();

                    b.ToTable("OutfitAttributes");
                });

            modelBuilder.Entity("EXE201.Repository.Models.OutfitImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OutfitId")
                        .HasColumnType("int");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ImageId")
                        .HasName("PK__OutfitIm__7516F70C426EFF01");

                    b.HasIndex("OutfitId");

                    b.ToTable("OutfitImages");
                });

            modelBuilder.Entity("EXE201.Repository.Models.OutfitSize", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"));

                    b.Property<double?>("ChestMaxCm")
                        .HasColumnType("float");

                    b.Property<double?>("HipMaxCm")
                        .HasColumnType("float");

                    b.Property<int>("OutfitId")
                        .HasColumnType("int");

                    b.Property<string>("SizeLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<double?>("WaistMaxCm")
                        .HasColumnType("float");

                    b.HasKey("SizeId")
                        .HasName("PK__OutfitSi__83BD097A6DB2F042");

                    b.HasIndex("OutfitId");

                    b.ToTable("OutfitSizes");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PaymentTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A385CBECA29");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("EXE201.Repository.Models.RentalPackage", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<double?>("DepositPercent")
                        .HasColumnType("float");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("OverdueFeePerHour")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<double>("PriceFactor")
                        .HasColumnType("float");

                    b.Property<double?>("WeekendSurchargePercent")
                        .HasColumnType("float");

                    b.HasKey("PackageId")
                        .HasName("PK__RentalPa__322035CCD1B957BC");

                    b.ToTable("RentalPackages");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("OutfitId")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79CED9263253");

                    b.HasIndex("OutfitId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EXE201.Repository.Models.ReviewImage", b =>
                {
                    b.Property<int>("ImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImgId"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.HasKey("ImgId")
                        .HasName("PK__ReviewIm__352F54F3D3525B2D");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewImages");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1AC3E18994");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EXE201.Repository.Models.ServiceAddon", b =>
                {
                    b.Property<int>("AddonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddonId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ServicePkgId")
                        .HasColumnType("int");

                    b.HasKey("AddonId")
                        .HasName("PK__ServiceA__742895331CFB5E56");

                    b.HasIndex("ServicePkgId");

                    b.ToTable("ServiceAddons");
                });

            modelBuilder.Entity("EXE201.Repository.Models.ServiceBooking", b =>
                {
                    b.Property<int>("SvcBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SvcBookingId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("ServicePkgId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ServiceTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SvcBookingId")
                        .HasName("PK__ServiceB__05C39E96AD27D33E");

                    b.HasIndex("BookingId");

                    b.HasIndex("ServicePkgId");

                    b.HasIndex("UserId");

                    b.ToTable("ServiceBookings");
                });

            modelBuilder.Entity("EXE201.Repository.Models.ServiceBookingAddon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddonId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PriceAtBooking")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SvcBookingId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ServiceB__3214EC07D2E91926");

                    b.HasIndex("AddonId");

                    b.HasIndex("SvcBookingId");

                    b.ToTable("ServiceBookingAddons");
                });

            modelBuilder.Entity("EXE201.Repository.Models.ServicePackage", b =>
                {
                    b.Property<int>("ServicePkgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicePkgId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StudioId")
                        .HasColumnType("int");

                    b.HasKey("ServicePkgId")
                        .HasName("PK__ServiceP__97092E97BB94F7B7");

                    b.HasIndex("StudioId");

                    b.ToTable("ServicePackages");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Studio", b =>
                {
                    b.Property<int>("StudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudioId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StudioId")
                        .HasName("PK__Studios__4ACC3B7034C51072");

                    b.ToTable("Studios");
                });

            modelBuilder.Entity("EXE201.Repository.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C2A97CA98");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053439BEFE40")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EXE201.Repository.Models.UserAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressLine")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AddressId")
                        .HasName("PK__UserAddr__091C2AFB5948119B");

                    b.HasIndex(new[] { "UserId" }, "IX_UserAddresses_UserId");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Wishlist", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistId"));

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("OutfitId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WishlistId")
                        .HasName("PK__Wishlist__233189EB98352EAE");

                    b.HasIndex("OutfitId");

                    b.HasIndex("UserId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Booking", b =>
                {
                    b.HasOne("EXE201.Repository.Models.UserAddress", "Address")
                        .WithMany("Bookings")
                        .HasForeignKey("AddressId")
                        .HasConstraintName("FK_Bookings_UserAddresses");

                    b.HasOne("EXE201.Repository.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Users");

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EXE201.Repository.Models.BookingDetail", b =>
                {
                    b.HasOne("EXE201.Repository.Models.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingDetails_Bookings");

                    b.HasOne("EXE201.Repository.Models.OutfitSize", "OutfitSize")
                        .WithMany("BookingDetails")
                        .HasForeignKey("OutfitSizeId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingDetails_Sizes");

                    b.HasOne("EXE201.Repository.Models.RentalPackage", "RentalPackage")
                        .WithMany("BookingDetails")
                        .HasForeignKey("RentalPackageId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingDetails_Packages");

                    b.Navigation("Booking");

                    b.Navigation("OutfitSize");

                    b.Navigation("RentalPackage");
                });

            modelBuilder.Entity("EXE201.Repository.Models.DepositTransaction", b =>
                {
                    b.HasOne("EXE201.Repository.Models.Booking", "Booking")
                        .WithMany("DepositTransactions")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_Deposits_Bookings");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("EXE201.Repository.Models.LoyaltyTransaction", b =>
                {
                    b.HasOne("EXE201.Repository.Models.User", "User")
                        .WithMany("LoyaltyTransactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Loyalty_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Outfit", b =>
                {
                    b.HasOne("EXE201.Repository.Models.Category", "Category")
                        .WithMany("Outfits")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Outfits_Categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EXE201.Repository.Models.OutfitAttribute", b =>
                {
                    b.HasOne("EXE201.Repository.Models.Outfit", "Outfit")
                        .WithOne("OutfitAttribute")
                        .HasForeignKey("EXE201.Repository.Models.OutfitAttribute", "OutfitId")
                        .IsRequired()
                        .HasConstraintName("FK_Attributes_Outfits");

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("EXE201.Repository.Models.OutfitImage", b =>
                {
                    b.HasOne("EXE201.Repository.Models.Outfit", "Outfit")
                        .WithMany("OutfitImages")
                        .HasForeignKey("OutfitId")
                        .IsRequired()
                        .HasConstraintName("FK_Images_Outfits");

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("EXE201.Repository.Models.OutfitSize", b =>
                {
                    b.HasOne("EXE201.Repository.Models.Outfit", "Outfit")
                        .WithMany("OutfitSizes")
                        .HasForeignKey("OutfitId")
                        .IsRequired()
                        .HasConstraintName("FK_Sizes_Outfits");

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Payment", b =>
                {
                    b.HasOne("EXE201.Repository.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Bookings");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Review", b =>
                {
                    b.HasOne("EXE201.Repository.Models.Outfit", "Outfit")
                        .WithMany("Reviews")
                        .HasForeignKey("OutfitId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Outfits");

                    b.HasOne("EXE201.Repository.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Users");

                    b.Navigation("Outfit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EXE201.Repository.Models.ReviewImage", b =>
                {
                    b.HasOne("EXE201.Repository.Models.Review", "Review")
                        .WithMany("ReviewImages")
                        .HasForeignKey("ReviewId")
                        .IsRequired()
                        .HasConstraintName("FK_ReviewImages_Reviews");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("EXE201.Repository.Models.ServiceAddon", b =>
                {
                    b.HasOne("EXE201.Repository.Models.ServicePackage", "ServicePkg")
                        .WithMany("ServiceAddons")
                        .HasForeignKey("ServicePkgId")
                        .IsRequired()
                        .HasConstraintName("FK_Addons_Services");

                    b.Navigation("ServicePkg");
                });

            modelBuilder.Entity("EXE201.Repository.Models.ServiceBooking", b =>
                {
                    b.HasOne("EXE201.Repository.Models.Booking", "Booking")
                        .WithMany("ServiceBookings")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK_SvcBookings_ParentBooking");

                    b.HasOne("EXE201.Repository.Models.ServicePackage", "ServicePkg")
                        .WithMany("ServiceBookings")
                        .HasForeignKey("ServicePkgId")
                        .IsRequired()
                        .HasConstraintName("FK_SvcBookings_Pkg");

                    b.HasOne("EXE201.Repository.Models.User", "User")
                        .WithMany("ServiceBookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_SvcBookings_Users");

                    b.Navigation("Booking");

                    b.Navigation("ServicePkg");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EXE201.Repository.Models.ServiceBookingAddon", b =>
                {
                    b.HasOne("EXE201.Repository.Models.ServiceAddon", "Addon")
                        .WithMany("ServiceBookingAddons")
                        .HasForeignKey("AddonId")
                        .IsRequired()
                        .HasConstraintName("FK_SvcDetails_Addon");

                    b.HasOne("EXE201.Repository.Models.ServiceBooking", "SvcBooking")
                        .WithMany("ServiceBookingAddons")
                        .HasForeignKey("SvcBookingId")
                        .IsRequired()
                        .HasConstraintName("FK_SvcDetails_Booking");

                    b.Navigation("Addon");

                    b.Navigation("SvcBooking");
                });

            modelBuilder.Entity("EXE201.Repository.Models.ServicePackage", b =>
                {
                    b.HasOne("EXE201.Repository.Models.Studio", "Studio")
                        .WithMany("ServicePackages")
                        .HasForeignKey("StudioId")
                        .IsRequired()
                        .HasConstraintName("FK_Services_Studios");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("EXE201.Repository.Models.User", b =>
                {
                    b.HasOne("EXE201.Repository.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EXE201.Repository.Models.UserAddress", b =>
                {
                    b.HasOne("EXE201.Repository.Models.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserAddresses_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Wishlist", b =>
                {
                    b.HasOne("EXE201.Repository.Models.Outfit", "Outfit")
                        .WithMany("Wishlists")
                        .HasForeignKey("OutfitId")
                        .IsRequired()
                        .HasConstraintName("FK_Wishlists_Outfits");

                    b.HasOne("EXE201.Repository.Models.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Wishlists_Users");

                    b.Navigation("Outfit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Booking", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("DepositTransactions");

                    b.Navigation("Payments");

                    b.Navigation("ServiceBookings");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Category", b =>
                {
                    b.Navigation("Outfits");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Outfit", b =>
                {
                    b.Navigation("OutfitAttribute");

                    b.Navigation("OutfitImages");

                    b.Navigation("OutfitSizes");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("EXE201.Repository.Models.OutfitSize", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("EXE201.Repository.Models.RentalPackage", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Review", b =>
                {
                    b.Navigation("ReviewImages");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EXE201.Repository.Models.ServiceAddon", b =>
                {
                    b.Navigation("ServiceBookingAddons");
                });

            modelBuilder.Entity("EXE201.Repository.Models.ServiceBooking", b =>
                {
                    b.Navigation("ServiceBookingAddons");
                });

            modelBuilder.Entity("EXE201.Repository.Models.ServicePackage", b =>
                {
                    b.Navigation("ServiceAddons");

                    b.Navigation("ServiceBookings");
                });

            modelBuilder.Entity("EXE201.Repository.Models.Studio", b =>
                {
                    b.Navigation("ServicePackages");
                });

            modelBuilder.Entity("EXE201.Repository.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("LoyaltyTransactions");

                    b.Navigation("Reviews");

                    b.Navigation("ServiceBookings");

                    b.Navigation("UserAddresses");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("EXE201.Repository.Models.UserAddress", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
