// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EXE201.Repository.Models;

public partial class ClothingRentalDbContext : DbContext
{
    public ClothingRentalDbContext(DbContextOptions<ClothingRentalDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Address> Addresses { get; set; }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<BookingDetail> BookingDetails { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<DepositTransaction> DepositTransactions { get; set; }

    public virtual DbSet<LoyaltyTransaction> LoyaltyTransactions { get; set; }

    public virtual DbSet<Outfit> Outfits { get; set; }

    public virtual DbSet<OutfitAttribute> OutfitAttributes { get; set; }

    public virtual DbSet<OutfitImage> OutfitImages { get; set; }

    public virtual DbSet<OutfitSize> OutfitSizes { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<RentalPackage> RentalPackages { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<ReviewImage> ReviewImages { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<ServiceAddon> ServiceAddons { get; set; }

    public virtual DbSet<ServiceBooking> ServiceBookings { get; set; }

    public virtual DbSet<ServiceBookingAddon> ServiceBookingAddons { get; set; }

    public virtual DbSet<ServicePackage> ServicePackages { get; set; }

    public virtual DbSet<Studio> Studios { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Wishlist> Wishlists { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Address>(entity =>
        {
            entity.HasKey(e => e.AddressId).HasName("PK__Address__091C2AFBB5DDBFDF");

            entity.ToTable("Address");

            entity.HasIndex(e => e.UserId, "IX_Address_UserId");

            entity.Property(e => e.AddressText)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.User).WithMany(p => p.Addresses)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Address_Users");
        });

        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK__Bookings__73951AEDF13EB55C");

            entity.Property(e => e.AddressText).HasMaxLength(255);
            entity.Property(e => e.BookingDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PaymentStatus).HasMaxLength(50);
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.TotalDepositAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalRentalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalSurcharge).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Address).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.AddressId)
                .HasConstraintName("FK_Bookings_Address");

            entity.HasOne(d => d.User).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bookings_Users");
        });

        modelBuilder.Entity<BookingDetail>(entity =>
        {
            entity.HasKey(e => e.DetailId).HasName("PK__BookingD__135C316DA54F4BA2");

            entity.Property(e => e.DamageFee)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DepositAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.LateFee)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.StartTime).HasColumnType("datetime");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Booking).WithMany(p => p.BookingDetails)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingDetails_Bookings");

            entity.HasOne(d => d.OutfitSize).WithMany(p => p.BookingDetails)
                .HasForeignKey(d => d.OutfitSizeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingDetails_Sizes");

            entity.HasOne(d => d.RentalPackage).WithMany(p => p.BookingDetails)
                .HasForeignKey(d => d.RentalPackageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingDetails_Packages");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Categori__19093A0BA517F0AB");

            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<DepositTransaction>(entity =>
        {
            entity.HasKey(e => e.TransId).HasName("PK__DepositT__9E5DDB3CB8D8E7FB");

            entity.Property(e => e.AmountDeducted).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.AmountHeld).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.AmountRefunded).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DeductionReason).HasMaxLength(255);
            entity.Property(e => e.ProcessedAt).HasColumnType("datetime");
            entity.Property(e => e.Status).HasMaxLength(50);

            entity.HasOne(d => d.Booking).WithMany(p => p.DepositTransactions)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Deposits_Bookings");
        });

        modelBuilder.Entity<LoyaltyTransaction>(entity =>
        {
            entity.HasKey(e => e.TransactionId).HasName("PK__LoyaltyT__55433A6BCB11CFDE");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.TransactionType).HasMaxLength(50);

            entity.HasOne(d => d.User).WithMany(p => p.LoyaltyTransactions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Loyalty_Users");
        });

        modelBuilder.Entity<Outfit>(entity =>
        {
            entity.HasKey(e => e.OutfitId).HasName("PK__Outfits__399B99B1FC886C58");

            entity.Property(e => e.BaseRentalPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Gender).HasMaxLength(20);
            entity.Property(e => e.IsLimited).HasDefaultValue(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Region).HasMaxLength(100);
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.Type).HasMaxLength(100);

            entity.HasOne(d => d.Category).WithMany(p => p.Outfits)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Outfits_Categories");
        });

        modelBuilder.Entity<OutfitAttribute>(entity =>
        {
            entity.HasKey(e => e.DetailId).HasName("PK__OutfitAt__135C316D8D9C4EE8");

            entity.HasIndex(e => e.OutfitId, "UQ__OutfitAt__399B99B006B219CC").IsUnique();

            entity.Property(e => e.ColorPrimary).HasMaxLength(100);
            entity.Property(e => e.CulturalOrigin).HasMaxLength(255);
            entity.Property(e => e.FormalityLevel).HasMaxLength(100);
            entity.Property(e => e.Material).HasMaxLength(255);
            entity.Property(e => e.Occasion).HasMaxLength(255);
            entity.Property(e => e.SeasonSuitability).HasMaxLength(100);
            entity.Property(e => e.Silhouette).HasMaxLength(255);
            entity.Property(e => e.StoryTitle).HasMaxLength(255);

            entity.HasOne(d => d.Outfit).WithOne(p => p.OutfitAttribute)
                .HasForeignKey<OutfitAttribute>(d => d.OutfitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Attributes_Outfits");
        });

        modelBuilder.Entity<OutfitImage>(entity =>
        {
            entity.HasKey(e => e.ImageId).HasName("PK__OutfitIm__7516F70CB3751FA9");

            entity.Property(e => e.ImageType).HasMaxLength(50);
            entity.Property(e => e.ImageUrl).IsRequired();

            entity.HasOne(d => d.Outfit).WithMany(p => p.OutfitImages)
                .HasForeignKey(d => d.OutfitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Images_Outfits");
        });

        modelBuilder.Entity<OutfitSize>(entity =>
        {
            entity.HasKey(e => e.SizeId).HasName("PK__OutfitSi__83BD097AAE1EEF4A");

            entity.Property(e => e.SizeLabel)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.StockQuantity).HasDefaultValue(0);

            entity.HasOne(d => d.Outfit).WithMany(p => p.OutfitSizes)
                .HasForeignKey(d => d.OutfitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sizes_Outfits");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payments__9B556A389F25063E");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PaymentMethod).HasMaxLength(50);
            entity.Property(e => e.PaymentTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.TransactionRef).HasMaxLength(100);

            entity.HasOne(d => d.Booking).WithMany(p => p.Payments)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payments_Bookings");
        });

        modelBuilder.Entity<RentalPackage>(entity =>
        {
            entity.HasKey(e => e.PackageId).HasName("PK__RentalPa__322035CC30222FA7");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.OverdueFeePerHour).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__Reviews__74BC79CE3602D95E");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Outfit).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.OutfitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reviews_Outfits");

            entity.HasOne(d => d.User).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reviews_Users");
        });

        modelBuilder.Entity<ReviewImage>(entity =>
        {
            entity.HasKey(e => e.ImgId).HasName("PK__ReviewIm__352F54F355863906");

            entity.HasOne(d => d.Review).WithMany(p => p.ReviewImages)
                .HasForeignKey(d => d.ReviewId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReviewImages_Reviews");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE1ADF858ACD");

            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<ServiceAddon>(entity =>
        {
            entity.HasKey(e => e.AddonId).HasName("PK__ServiceA__742895337B32F894");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.ServicePkg).WithMany(p => p.ServiceAddons)
                .HasForeignKey(d => d.ServicePkgId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Addons_Services");
        });

        modelBuilder.Entity<ServiceBooking>(entity =>
        {
            entity.HasKey(e => e.SvcBookingId).HasName("PK__ServiceB__05C39E96E0545274");

            entity.Property(e => e.ServiceTime).HasColumnType("datetime");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.TotalPrice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Booking).WithMany(p => p.ServiceBookings)
                .HasForeignKey(d => d.BookingId)
                .HasConstraintName("FK_SvcBookings_ParentBooking");

            entity.HasOne(d => d.ServicePkg).WithMany(p => p.ServiceBookings)
                .HasForeignKey(d => d.ServicePkgId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SvcBookings_Pkg");

            entity.HasOne(d => d.User).WithMany(p => p.ServiceBookings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SvcBookings_Users");
        });

        modelBuilder.Entity<ServiceBookingAddon>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ServiceB__3214EC07335BC087");

            entity.Property(e => e.PriceAtBooking).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Addon).WithMany(p => p.ServiceBookingAddons)
                .HasForeignKey(d => d.AddonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SvcDetails_Addon");

            entity.HasOne(d => d.SvcBooking).WithMany(p => p.ServiceBookingAddons)
                .HasForeignKey(d => d.SvcBookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SvcDetails_Booking");
        });

        modelBuilder.Entity<ServicePackage>(entity =>
        {
            entity.HasKey(e => e.ServicePkgId).HasName("PK__ServiceP__97092E973FDE74D7");

            entity.Property(e => e.BasePrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Studio).WithMany(p => p.ServicePackages)
                .HasForeignKey(d => d.StudioId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Services_Studios");
        });

        modelBuilder.Entity<Studio>(entity =>
        {
            entity.HasKey(e => e.StudioId).HasName("PK__Studios__4ACC3B70C8838308");

            entity.Property(e => e.ContactInfo).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4C3B572EBC");

            entity.HasIndex(e => e.Email, "UQ__Users__A9D1053495EB44DA").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FullName).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PasswordHash).IsRequired();
            entity.Property(e => e.PhoneNumber).HasMaxLength(20);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Users_Roles");
        });

        modelBuilder.Entity<Wishlist>(entity =>
        {
            entity.HasKey(e => e.WishlistId).HasName("PK__Wishlist__233189EBB7826477");

            entity.Property(e => e.AddedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Outfit).WithMany(p => p.Wishlists)
                .HasForeignKey(d => d.OutfitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Wishlists_Outfits");

            entity.HasOne(d => d.User).WithMany(p => p.Wishlists)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Wishlists_Users");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}