// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXE201.Repository.Models;

public partial class OutfitAttribute
{
    public int DetailId { get; set; }

    public int OutfitId { get; set; }

    public string Material { get; set; }

    public string Silhouette { get; set; }

    public string FormalityLevel { get; set; }

    public string Occasion { get; set; }

    public string ColorPrimary { get; set; }

    public string SeasonSuitability { get; set; }

    public string StoryTitle { get; set; }

    public string StoryContent { get; set; }

    public string CulturalOrigin { get; set; }

    public virtual Outfit Outfit { get; set; }
}