// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXE201.Repository.Models;

public partial class Studio
{
    public int StudioId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string ContactInfo { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<ServicePackage> ServicePackages { get; set; } = new List<ServicePackage>();
}