// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXE201.Repository.Models;

public partial class UserAddress
{
    public int AddressId { get; set; }

    public int UserId { get; set; }

    public string Label { get; set; }

    public string RecipientName { get; set; }

    public string PhoneNumber { get; set; }

    public string AddressLine { get; set; }

    public string Ward { get; set; }

    public string District { get; set; }

    public string City { get; set; }

    public bool? IsDefault { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual User User { get; set; }
}